AxisCommunications/acap-documentation

- docs/introduction/acap-examples.md
> docs(acap examples): fix typo

- CODE_OF_CONDUCT.md
Closes #36
Change-Id: Ife91f0b2fe9067a6a6b6cc7d4e6b1c93b2fe65dd
Signed-off-by: Joakim Roubert <joakimr@axis.com>
> CODE_OF_CONDUCT.md: Fix markdown issues

- docs/introduction/sdk-overview.md
- docs/release-notes/4.0.md
- docs/release-notes/4.0_beta1.md
- docs/release-notes/4.1.md
> docs: markdown link style

- .github/workflows/build-dockerfiles.yml
- CODEOWNERS
> Sync 20220308 5

- docs/develop/app-project-structure.md
Close AxisCommunications/acap-documentation#23,
close AxisCommunications/acap-documentation#24
> Update manifest from scratch example

- CONTRIBUTING.md
- docs/develop/manifest-schemas.md
- docs/develop/schema-field-descriptions-v1.0.md
- docs/develop/schema-field-descriptions-v1.1.md
- docs/develop/schema-field-descriptions-v1.2.md
- docs/develop/schema-field-descriptions-v1.3.md
Close AxisCommunications/acap-documentation#42
> Add information of auto-generated content

- docs/api/beta-api.md
- docs/api/cv-api.md
- docs/develop/build-install-run.md
- docs/develop/web-server.md
- docs/get-started/hello-world.md
- docs/release-notes/4.2.md
> Sync 20220628 1

- docs/develop/build-install-run.md
- docs/develop/supported-languages.md
- docs/get-started/choose-sdk.md
- docs/release-notes/4.0.md
- docs/release-notes/4.0_beta1.md
- docs/release-notes/4.1.md
- docs/release-notes/4.2.md
- docs/release-notes/4.3.md
- docs/release-notes/4.4.md
> Sync 20221031 1

- .github/workflows/build-dockerfiles.yml
- .github/workflows/lint.yml
- Gemfile
- docs/develop/application-project-structure.md
- docs/faq/security.md
- docs/service/acap-application-signing.md
> Sync 20230424 1

- docs/service/acap-application-signing.md
> Sync 20230525 2

- docs/develop/VAPIX-access-for-ACAP-applications.md
- docs/develop/setting-up-visual-studio-code.md
- docs/develop/supported-languages.md
- docs/introduction/acap-sdk-overview.md
Syncing the staging repo to public
> Sync 20230922 1

- docs/api/computer-vision-sdk-apis.md
- docs/axis-devices-and-compatibility/index.md
- docs/develop/setting-up-visual-studio-code.md
- docs/release-notes/4.3.md
- Updating from larod-inference-server to acap-runtime (#218)
- Update setting-up-visual-studio-code.md (#217)
> sync 20231004 1

- docs/develop/setting-up-visual-studio-code.md
> Sync 20231009 1

- docs/api/computer-vision-sdk-apis.md
- docs/api/native-sdk-api.md
- docs/axis-devices-and-compatibility/index.md
Fixes AxisCommunications/acap-documentation#91
> Updated software compatibility section (#226)

- docs/develop/setting-up-visual-studio-code.md
Please include a summary of the change, a relevant motivation and context.
- Fixes #(issue)
> Sync 20231212 1

- 3.5/api/axparameter/html/ax__parameter_8h.html
- docs/develop/VAPIX-access-for-ACAP-applications.md
- Add axparameter changes to temp acap3 folder (#254)
- develop: Fix VAPIX code example errors (#255)
> sync 20240201 1

- docs/acap-sdk-version-3/develop-applications/vapix-access-for-acap-applications.md
- docs/develop/VAPIX-access-for-ACAP-applications.md
- docs/release-notes/4.13.md
- release-notes/4.13: Update and clarify information (#269)
- Update VAPIX access information (#268)
> sync 20240305 1

- Gemfile
- Fix axparameter broken link (#271)
- Fix broken link in 4.13 release note (#270)
- chore(deps): update dependency github-pages to v231 (#260)
> sync 20240328 1

- docs/api/computer-vision-sdk-apis.md
- docs/develop/supported-languages.md
- docs/introduction/acap4-vs-acap3.md
- docs/release-notes/4.13.md
- **acap4-vs-acap3: Update status for axparameter (#275)**
- **Update documentation after videocapture update and cpp deprecation (#274)**
> sync 20240425 2

- docs/computer-vision-on-device/test-your-model.md
- docs/get-started/set-up-developer-environment/set-up-device.md
- docs/introduction/acap-examples.md
Please include a summary of the change, a relevant motivation and context.
- Fixes #(issue)
> Sync 20240506 1

- .github/lint-device-urls.sh
- .github/workflows/lint.yml
- docs/acap-sdk-version-3/develop-applications/vapix-access-for-acap-applications.md
- docs/acap-sdk-version-3/get-started/set-up-the-device.md
- docs/develop/VAPIX-access-for-ACAP-applications.md
- docs/get-started/set-up-developer-environment/set-up-device-advanced.md
- docs/get-started/set-up-developer-environment/set-up-device.md
- **Remove mention of deprecated device (#290)**
- **Update device URLs (#291)**
- **set-up-developer-environment: Split out SSH section**
- **set-up-developer-environment: Add how to create SSH user**
- **Align curl commands and naming (#292)**
> sync 20240530 1

- .github/lint-device-urls.sh
- .textlintrc
- docs/acap-sdk-version-3/api/index.md
- docs/acap-sdk-version-3/get-started/set-up-the-device.md
- docs/develop/application-project-structure.md
- docs/develop/build-install-run.md
- docs/get-started/set-up-developer-environment/set-up-device-advanced.md
- **set-up-device-advanced: Fix broken link (#294)**
- **lint: Align to acap-native-sdk-examples linter (#299)**
- **lint: Add term AXIS OS (#300)**
- **lint: Align device url check to native examples (#301)**
- **lint: Change textlint to use walk-through (#302)**
- **Add OTHERFILES to mapping list (#304)**
> sync 20240618 1

- .textlintrc
- docs/acap-sdk-version-3/develop-applications/vapix-access-for-acap-applications.md
- docs/api/native-sdk-api.md
- docs/computer-vision-on-device/dlpu-model-conversion.md
- docs/computer-vision-on-device/optimization-tips.md
- docs/computer-vision-on-device/quantization.md
- docs/computer-vision-on-device/recommended-model-architecture.md
- docs/develop/VAPIX-access-for-ACAP-applications.md
- docs/develop/user-selection.md
- docs/introduction/acap-sdk-overview.md
- docs/release-notes/4.1.md
- docs/release-notes/4.13.md
- docs/release-notes/4.2.md
- **Guidance for ACAP transfer from using static "sdk" user to dynamic user (#295)**
- **lint: Add terms ARTPEC and VAPIX**
- **lint: Add some rules for ACAP, but not fully covered**
- **lint: Extend ARTPEC regex to include version**
- **lint: Add term YOLO**
> sync 20240625 1

- docs/acap-sdk-version-3/develop-applications/vapix-access-for-acap-applications.md
- docs/develop/VAPIX-access-for-ACAP-applications.md
- **fix: Update vapix access sample output**
- **VAPIX access: Update incorrect details in version history**
- **VAPIX access: Align ACAP 3 and 4**
> sync 20240704 2

- docs/acap-sdk-version-3/develop-applications/vapix-access-for-acap-applications.md
- docs/develop/VAPIX-access-for-ACAP-applications.md
- docs/get-started/set-up-developer-environment/set-up-device-advanced.md
- docs/get-started/set-up-developer-environment/set-up-device.md
Co-authored-by: pataxis <pataxis@users.noreply.github.com>
> Improve code block commands for copy to command-line (#317)

- Gemfile
- docs/api/computer-vision-sdk-apis.md
- docs/api/native-sdk-api.md
- docs/axis-devices-and-compatibility/index.md
- docs/faq/machine-learning.md
- docs/service/acap-application-signing.md
- **Update signing behavior for 12.0 (#318)**
- **Rephrase section on ACAP Runtime (#314)**
- **chore(deps): update dependency just-the-docs to "~> 0.9.0" (#320)**
- **Clarify supported products on the Native API page (#323)**
- **chore(deps): update dependency just-the-docs to "~> 0.10.0" (#328)**
- **Update machine learning FAQ (#327)**
- **Update product selector links (#329)**
> sync 20240917 1

- docs/release-notes/12.0.md
Co-authored-by: pataxis <pataxis@users.noreply.github.com>
> Release notes 12.0: Fix link to message-broker (#345)

- docs/acap-sdk-version-3/get-started/set-up-the-device.md
- docs/get-started/hello-world-example.md
- docs/introduction/what-is-acap.md
Please include a summary of the change, a relevant motivation and context.
- Fixes #(issue)
> Sync 20241104 3

- .github/super-linter.env
- .github/workflows/lint.yml
- .textlintrc
- CONTRIBUTING.md
- TROUBLESHOOTING.md
- docs/acap-sdk-version-3/develop-applications/application-project-structure.md
- docs/acap-sdk-version-3/get-started/acap-development-requirements.md
- docs/api/computer-vision-sdk-apis.md
- docs/api/native-sdk-api.md
- docs/develop/setting-up-visual-studio-code.md
- docs/faq/deployment.md
- docs/release-notes/4.14.md
- **chore(deps): update super-linter/super-linter action to v7 (#326)**
- **fix consume-scene-metadata-example broken link (#350)**
> sync 20241120 1

- docs/develop/global-device-proxy.md
- docs/develop/manifest-schemas/index.md
- **global-device-proxy: Update index to last in line (#357)**
- **manifest-schemas: Add code formatting of architecure (#358)**
> sync 20241205 2

- docs/get-started/set-up-developer-environment/set-up-device-advanced.md
Co-authored-by: pataxis <pataxis@users.noreply.github.com>
> get-started: Update broken link to OAK API (#363)
